/*
 * Copyright (c) 2026 Hachist Robotics
 * Author: wanglei@hachist.com
 * 上海哈船智能船舶技术有限公司
 * File: errors.h
 * Brief: C++17 view of the E_* closed set, byte-equal to the Python export
 *
 * Description:
 * GENERATED by scripts/gen/gen_errors.py from xbrain/common/errors/codes.yaml.
 * Do not edit by hand. A hand edit is reverted by the next regeneration, and
 * until then the two languages disagree about a code -- which compiles, runs,
 * and surfaces only during integration, when a peer branches on a spelling this
 * side got wrong. tests/common/test_cross_lang_codes.py fails on any difference
 * between the codes this header carries and the ones the Python package exports.
 *
 * What problem this solves. CLAUDE.md 3.5 requires every E_* constant to come
 * from the shared error library and forbids spelling it as a literal anywhere
 * else. The Python half of that library is xbrain/common/errors/; this is the
 * C++ half. Its consumers -- chassis_relay, quadruped, perception, rtk_driver --
 * need to name the same codes the Python processes name, and 19 S1.2 forbids
 * anything under common/ from pulling in rclcpp or any ROS type, because 11
 * S1.1.6 puts chassis_relay on the emergency-stop path under CRL-4 and CRL-5 and
 * a foundation header that dragged in ROS would be unusable there. Nothing below
 * leaves the C++17 standard library.
 *
 * Which section this implements. The closed set is 11 S13.4~S13.15 (grep the
 * group headings 13.4 A through 13.15 L). codes.yaml is the single source of
 * truth and is bound to those tables, in both directions, by the symmetric
 * difference metatest in tests/common/test_error_codes.py -- that metatest is
 * what establishes the codes are RIGHT. The cross-language check on this header
 * only establishes that the two languages carry the SAME codes; comparing a
 * generated artifact with its own generator is true by construction and proves
 * nothing on its own (CLAUDE.md 3.2 form 7).
 *
 * How to use it. Name a code by its constant, never by a string literal:
 *   if (result.code == hachist::xbrain::errors::kETimeout) { ... }
 * A literal "E_TIMEOUT" written at a call site is a second copy of the spelling
 * and is exactly what scripts/lint/no_literal_ecode.py rejects. kAllCodes is the
 * whole set as one table, so a consumer that has to walk every code -- a gateway
 * mapping transport status onto the set, say -- has one place to read.
 *
 * What this header deliberately does NOT do, so nothing gets bolted on:
 *   * it does not carry the meaning column. That column is Chinese contract
 *     prose for a human reading a log; putting it here would drag non-ASCII text
 *     and Chinese punctuation into a source file CLAUDE.md 2.2 holds to ASCII,
 *     and no consumer on the estop path reads it. It stays on the Python side.
 *   * it does not carry the S13.x group letter. group has no runtime consumer;
 *     its one reader is a Python metatest that catches a code being moved
 *     between contract sections, which is a codes.yaml-versus-document check,
 *     not a job for a deployed C++ header.
 *   * it does not throw and it does not map. The Python side raises on an
 *     unknown code; here there is no lookup that could -- a caller compares
 *     against the named constants it already holds. Mapping a transport status
 *     onto a code is the gateway's job (11 S8.13.5, grep 错误映射), not this
 *     header's, so there is deliberately no Classify() to bolt policy onto.
 *   * it does not expose the retryable or detail vocabularies as named
 *     constants. They are carried per code below as plain strings for a consumer
 *     to branch on; a symbolic constant for them earns its place the day a C++
 *     consumer needs one, not before (CLAUDE.md 9.3).
 *
 * The two ways to read this that look right and are not:
 *   1. reordering the table into contract or group order because it "reads
 *      better". The order here is a plain sort by code, chosen for one reason:
 *      the Python golden test iterates sorted(ALL_CODES), so any other order
 *      makes the byte comparison fail for a reason that is not a defect. Change
 *      the order here and you must change it there, in lockstep, or the gate
 *      goes red.
 *   2. treating retryable as a display hint. 11 S13.2 calls it a SAFETY column:
 *      a cloud client that resends a non-retryable E_LOCKED (HES not cleared) at
 *      10 Hz is issuing motion commands into a locked machine. The values here
 *      are the contract's classification, not advice.
 */

#ifndef HACHIST_XBRAIN_V6_COMMON_ERRORS_ERRORS_H_
#define HACHIST_XBRAIN_V6_COMMON_ERRORS_ERRORS_H_

/* string_view for the values and nothing else. Every include here is one every
 * consumer pays for, and one of those consumers is on a hop CRL-5 budgets at
 * 200 microseconds. No <string>: these are all views over string literals with
 * static storage, so nothing here allocates. */
#include <string_view>

namespace hachist {
namespace xbrain {
namespace errors {

/* One row of the closed set, as much of 11 S13.4~S13.15 as a C++ consumer on the
 * estop path needs. Three fields, not five: meaning and group stay on the Python
 * side for the reasons in the file header.
 *
 * All three are string_view over a string literal, so an ErrorCode is a trio of
 * pointers with static lifetime and copying one costs nothing. retryable and
 * detail are the contract's own vocabulary, spelled exactly as codes.yaml spells
 * them so the same text reaches both languages:
 *   retryable  one of "yes" | "conditional" | "no" | "n_a"  (11 S13.2, a SAFETY
 *              column -- see the file header)
 *   detail     one of "required" | "implied" | "unspecified"  (EC-3) */
struct ErrorCode {
  std::string_view code;       // the wire value, identical to the named constant
  std::string_view retryable;  // "yes" | "conditional" | "no" | "n_a"
  std::string_view detail;     // "required" | "implied" | "unspecified"
};

// One named constant per code, so a C++ consumer names E_TIMEOUT
// rather than spelling it, exactly as the Python package binds
// the name (CLAUDE.md 3.5). The string IS the wire value.
inline constexpr std::string_view kEArbDisabled = "E_ARB_DISABLED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEArbDisarmed = "E_ARB_DISARMED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEArbLeaseExpired = "E_ARB_LEASE_EXPIRED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEArbNoDomain = "E_ARB_NO_DOMAIN";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEArbNoSource = "E_ARB_NO_SOURCE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEBusy = "E_BUSY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kECapability = "E_CAPABILITY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEChannelDenied = "E_CHANNEL_DENIED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEConfigInvalid = "E_CONFIG_INVALID";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEConfigLocked = "E_CONFIG_LOCKED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEConfirmRequired = "E_CONFIRM_REQUIRED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEDegraded = "E_DEGRADED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEDuplicate = "E_DUPLICATE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEFenceInvalid = "E_FENCE_INVALID";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEGeoConflict = "E_GEO_CONFLICT";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEGeoIncomplete = "E_GEO_INCOMPLETE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEGeoInvalid = "E_GEO_INVALID";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEGeoTooLarge = "E_GEO_TOO_LARGE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEInternal = "E_INTERNAL";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kELocked = "E_LOCKED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kELowBattery = "E_LOW_BATTERY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kENameConflict = "E_NAME_CONFLICT";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kENotFound = "E_NOT_FOUND";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kENotImplemented = "E_NOT_IMPLEMENTED";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kENoHeading = "E_NO_HEADING";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEOutOfFence = "E_OUT_OF_FENCE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEProtoVersion = "E_PROTO_VERSION";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEQosViolation = "E_QOS_VIOLATION";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kESafetyLinkLost = "E_SAFETY_LINK_LOST";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kESchema = "E_SCHEMA";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEStatus = "E_STATUS";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEStorageCorrupt = "E_STORAGE_CORRUPT";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETaskState = "E_TASK_STATE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETeachBusy = "E_TEACH_BUSY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETeachGeometry = "E_TEACH_GEOMETRY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETeachQuality = "E_TEACH_QUALITY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETeachState = "E_TEACH_STATE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETeleopStale = "E_TELEOP_STALE";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kETimeout = "E_TIMEOUT";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kEUnhealthy = "E_UNHEALTHY";  // ECODE-OK(export): generated closed-set export
inline constexpr std::string_view kOk = "OK";

// The whole closed set as one table, in the same sort-by-code
// order the Python golden test iterates, so the two languages
// print byte-identical output without coordinating.
inline constexpr ErrorCode kAllCodes[] = {
    {kEArbDisabled, "no", "unspecified"},
    {kEArbDisarmed, "conditional", "unspecified"},
    {kEArbLeaseExpired, "yes", "unspecified"},
    {kEArbNoDomain, "no", "unspecified"},
    {kEArbNoSource, "no", "unspecified"},
    {kEBusy, "conditional", "unspecified"},
    {kECapability, "no", "unspecified"},
    {kEChannelDenied, "no", "unspecified"},
    {kEConfigInvalid, "no", "unspecified"},
    {kEConfigLocked, "no", "unspecified"},
    {kEConfirmRequired, "no", "unspecified"},
    {kEDegraded, "conditional", "unspecified"},
    {kEDuplicate, "n_a", "unspecified"},
    {kEFenceInvalid, "no", "implied"},
    {kEGeoConflict, "conditional", "unspecified"},
    {kEGeoIncomplete, "conditional", "required"},
    {kEGeoInvalid, "no", "implied"},
    {kEGeoTooLarge, "no", "unspecified"},
    {kEInternal, "conditional", "unspecified"},
    {kELocked, "conditional", "unspecified"},
    {kELowBattery, "conditional", "implied"},
    {kENameConflict, "conditional", "implied"},
    {kENotFound, "conditional", "unspecified"},
    {kENotImplemented, "no", "unspecified"},
    {kENoHeading, "conditional", "unspecified"},
    {kEOutOfFence, "conditional", "unspecified"},
    {kEProtoVersion, "no", "unspecified"},
    {kEQosViolation, "no", "implied"},
    {kESafetyLinkLost, "conditional", "unspecified"},
    {kESchema, "no", "unspecified"},
    {kEStatus, "conditional", "unspecified"},
    {kEStorageCorrupt, "no", "unspecified"},
    {kETaskState, "conditional", "implied"},
    {kETeachBusy, "conditional", "unspecified"},
    {kETeachGeometry, "conditional", "unspecified"},
    {kETeachQuality, "conditional", "unspecified"},
    {kETeachState, "conditional", "unspecified"},
    {kETeleopStale, "yes", "unspecified"},
    {kETimeout, "conditional", "unspecified"},
    {kEUnhealthy, "conditional", "unspecified"},
    {kOk, "n_a", "unspecified"},
};

}  // namespace errors
}  // namespace xbrain
}  // namespace hachist

#endif  // HACHIST_XBRAIN_V6_COMMON_ERRORS_ERRORS_H_
