"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: __init__.py
Brief: CHK-0-54 -- expose build_version to the runtime, read from the
       committed _build.py (generated by scripts/version/gen_build_version.py)

Description:
Why this exists as a package rather than a constant next to callers. CHK-0-54
requires ONE build_version reachable from Python code (startup logs use it,
rt/chassis/hello embeds it in the runtime block, tests assert it matches
`git describe`). Spreading the constant across call sites is exactly the
"hard-coded string" shape §3.2 form ① names: a change to git state would
have to be re-copied to every site and inevitably would not be, leaving
the runtime version claim silently stale.

Two shapes callers use:
  from xbrain.common.version import build_version
  from xbrain.common.version import BUILD_VERSION      # loud UPPER alias

The truth is in _build.py, a generated file the CI drift gate rebuilds and
diffs. When _build.py does not exist (fresh clone, sdist without the
generator having run), we fall back to the string "unknown-dev" so imports
do NOT explode -- but "unknown-dev" is a wire-facing string CI treats as
red, so a real deployment cannot silently ship it.

Traps -- things that look right and are not:
  1. Reading `git describe` at import time. That would work on a workstation
     and silently fail on an install root that has no .git dir. The generator
     runs at build time, writes _build.py, and this module only READS.
  2. Making unknown-dev an empty string. Empty concatenates cleanly into
     log lines and downstream JSON, hiding the drift. A visible token that
     CI treats as an error is the whole point.
"""

try:
    from xbrain.common.version._build import build_version
except ImportError:
    # Fresh clone / sdist without a generator run. Fallback is a VISIBLE
    # token, not empty (trap 2): tests/deploy/test_install_rollback.py
    # asserts a real deployment never ships this literal.
    build_version = "unknown-dev"

# Uppercase alias for callers that prefer the constant convention. Kept a
# reference to the SAME string so an assertion on identity holds.
BUILD_VERSION = build_version

__all__ = ["build_version", "BUILD_VERSION"]
