"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: _build.py
Brief: GENERATED by scripts/version/gen_build_version.py -- do not edit by hand

Description:
Committed snapshot of `git describe --always --dirty` + commit hash + commit
ISO date at the moment scripts/version/gen_build_version.py --write last ran.
CI drift gate: `python scripts/version/gen_build_version.py --check` refuses
commit when this file disagrees with the current git state.

Regenerate with:
    python scripts/version/gen_build_version.py --write
"""

build_version = '4cb99f1-dirty'
commit_sha = '4cb99f1f1b2128238c77aa405b525a5d149d92f8'
commit_date_iso = '2026-08-10T17:00:22+09:00'
