"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: _build.py
Brief: GENERATED by scripts/version/gen_build_version.py -- do not edit by hand

Description:
Committed snapshot of `git describe --always --dirty` + commit hash + commit
ISO date at the moment scripts/version/gen_build_version.py --write last ran.
CI drift gate: `python scripts/version/gen_build_version.py --check` refuses
commit when this file disagrees with the current git state.

Regenerate with:
    python scripts/version/gen_build_version.py --write
"""

build_version = '21e2d1e-dirty'
commit_sha = '21e2d1ef9d8e0c57adcbd88bd0a245fa2a2c0bd5'
commit_date_iso = '2026-08-10T19:11:24+09:00'
