/*
 * Copyright (c) 2026 Hachist Robotics
 * Author: wanglei@hachist.com
 * 上海哈船智能船舶技术有限公司
 * File: chs_b.cc
 * Brief: The domain-0 participant and its two readers (see chs_b.h)
 *
 * Description:
 * The bare CycloneDDS C API, used directly. Four lines here carry the whole
 * point of the file:
 *
 *   dds_create_domain(0, config_xml)     configuration INJECTED, not from
 *                                        CYCLONEDDS_URI (DDS-3)
 *   dds_create_participant(0, ...)       the domain passed EXPLICITLY, not from
 *                                        ROS_DOMAIN_ID (DDS-1)
 *   dds_create_reader(...)               readers only, never a writer (DDS-4)
 *   value copy in Poll                   no DDS-allocated object escapes (DDS-5)
 *
 * The first two exist because this process also holds an rclcpp context on
 * domain 42 and both environment variables are process-wide. One read collapses
 * the two domains, and the result is a participant that is up with no traffic.
 *
 * The configuration string enables multicast on this domain regardless of what
 * the ROS side is set to. 13 DDS-7 requires the two to be OPPOSITE: the uplink
 * runs with ROS_LOCALHOST_ONLY, and the chassis is a different machine on the
 * wire. A single global setting cannot satisfy both, which is the second reason
 * the configuration is per-domain rather than environmental.
 */

#include "quadruped/chs_b.h"

#include <cstring>
#include <stdexcept>
#include <string>

#include "dds/dds.h"

// Generated by idlc from ros2_ws/quadruped/idl/chassis_dds_types.idl at build
// time. The generated names carry the dds_ module and the trailing underscore
// that ROS 2 puts on the wire -- see the IDL's own comment for why the stock
// sensor_msgs IDL cannot be used directly.
#include "chassis_dds_types.h"

namespace quadruped {
namespace {

// Per-domain configuration, injected. NOT CYCLONEDDS_URI: that variable is
// process-wide and would also reach the rclcpp context on domain 42.
//
// Multicast stays on here even when the ROS side is confined to localhost
// (DDS-7): the chassis is another machine, and discovery has to leave this one.
const char* kDomainConfig =
    "<CycloneDDS><Domain><General>"
    "<AllowMulticast>true</AllowMulticast>"
    "</General></Domain></CycloneDDS>";

}  // namespace

struct ChassisDds::Impl {
  ChassisDdsConfig cfg;
  dds_entity_t domain = 0;
  dds_entity_t participant = 0;
  dds_entity_t imu_reader = 0;
  dds_entity_t motion_reader = 0;

  ImuSample imu;
  MotionInfoSample motion;
  bool has_imu = false;
  bool has_motion = false;
  std::uint64_t imu_count = 0;
  std::uint64_t motion_count = 0;
};

ChassisDds::ChassisDds(const ChassisDdsConfig& cfg) : impl_(new Impl()) {
  impl_->cfg = cfg;

  // ---- DDS-3: the configuration is injected, not read from the environment.
  impl_->domain = dds_create_domain(static_cast<dds_domainid_t>(cfg.domain_id),
                                    kDomainConfig);
  // DDS_RETCODE_PRECONDITION_NOT_MET means the domain already exists in this
  // process, which is fine: the participant below joins it either way.
  if (impl_->domain < 0 && impl_->domain != DDS_RETCODE_PRECONDITION_NOT_MET) {
    throw std::runtime_error(
        std::string("chassis DDS: could not create domain: ") +
        dds_strretcode(-impl_->domain));
  }

  // ---- DDS-1: the domain id, explicitly. Never ROS_DOMAIN_ID.
  impl_->participant = dds_create_participant(
      static_cast<dds_domainid_t>(cfg.domain_id), nullptr, nullptr);
  if (impl_->participant < 0) {
    throw std::runtime_error(
        std::string("chassis DDS: could not create the domain-") +
        std::to_string(cfg.domain_id) +
        " participant: " + dds_strretcode(-impl_->participant));
  }

  // The topic names go through the mapping in dds_names.h: /IMU is rt/IMU on
  // the wire, and a reader created with the ROS spelling matches nothing.
  const std::string imu_topic = RosTopicToDdsTopic(cfg.imu_topic);

  // BEST_EFFORT with a small history: the chassis publishes IMU BEST_EFFORT at
  // 200 Hz (measured 2026-09-15, 201 Hz), and a RELIABLE reader would simply
  // never match it -- QoS incompatibility is silent on both sides.
  dds_qos_t* qos = dds_create_qos();
  dds_qset_reliability(qos, DDS_RELIABILITY_BEST_EFFORT, 0);
  dds_qset_history(qos, DDS_HISTORY_KEEP_LAST, 1);

  const dds_entity_t imu_t = dds_create_topic(
      impl_->participant, &sensor_msgs_msg_dds__Imu__desc, imu_topic.c_str(),
      nullptr, nullptr);
  if (imu_t < 0) {
    dds_delete_qos(qos);
    throw std::runtime_error(std::string("chassis DDS: topic ") + imu_topic +
                             ": " + dds_strretcode(-imu_t));
  }
  // ---- DDS-4: a READER. There is no writer anywhere in this file.
  impl_->imu_reader = dds_create_reader(impl_->participant, imu_t, qos, nullptr);
  if (impl_->imu_reader < 0) {
    dds_delete_qos(qos);
    throw std::runtime_error(std::string("chassis DDS: reader on ") + imu_topic +
                             ": " + dds_strretcode(-impl_->imu_reader));
  }

  // /MOTION_INFO is RELIABLE on the chassis (measured), so its reader is too.
  // Getting this backwards is the same silent non-match as above, in the other
  // direction: a BEST_EFFORT reader does match a RELIABLE writer, so only the
  // IMU direction fails loudly-by-silence -- which is why both are stated.
  dds_qos_t* rqos = dds_create_qos();
  dds_qset_reliability(rqos, DDS_RELIABILITY_RELIABLE, DDS_SECS(1));
  dds_qset_history(rqos, DDS_HISTORY_KEEP_LAST, 1);
  const std::string mi_topic = RosTopicToDdsTopic("/MOTION_INFO");
  const dds_entity_t mi_t = dds_create_topic(
      impl_->participant, &drdds_msg_dds__MotionInfo__desc, mi_topic.c_str(),
      nullptr, nullptr);
  if (mi_t >= 0) {
    impl_->motion_reader = dds_create_reader(impl_->participant, mi_t, rqos, nullptr);
  }
  // A missing /MOTION_INFO is NOT fatal: 13 S7.4 makes drdds an enhancement,
  // and 13 S4.2 falls back to the monitor protocol's 10 Hz velocity. The IMU is
  // the one that must be there.
  dds_delete_qos(rqos);
  dds_delete_qos(qos);
}

ChassisDds::~ChassisDds() {
  if (!impl_) return;
  if (impl_->participant > 0) dds_delete(impl_->participant);
  if (impl_->domain > 0) dds_delete(impl_->domain);
}

int ChassisDds::Poll(double now_mono_s) {
  if (!impl_) return 0;
  int n = 0;

  {
    // dds_take with a loan, copied out immediately (DDS-5). The loan is
    // returned in the same scope: holding one across a thread boundary is how
    // a reader eventually stalls with its history full.
    void* raw[1] = {nullptr};
    dds_sample_info_t info[1];
    const dds_return_t rc =
        dds_take(impl_->imu_reader, raw, info, 1, 1);
    if (rc > 0 && info[0].valid_data) {
      const sensor_msgs_msg_dds__Imu_* m =
          static_cast<const sensor_msgs_msg_dds__Imu_*>(raw[0]);
      ImuSample s;
      s.wx = m->angular_velocity.x;
      s.wy = m->angular_velocity.y;
      s.wz = m->angular_velocity.z;
      s.qx = m->orientation.x;
      s.qy = m->orientation.y;
      s.qz = m->orientation.z;
      s.qw = m->orientation.w;
      s.ax = m->linear_acceleration.x;
      s.ay = m->linear_acceleration.y;
      s.az = m->linear_acceleration.z;
      // OUR receive time, on the monotonic clock. The publisher's stamp is that
      // machine's wall clock and cannot be compared with ours (CLK-C4).
      s.rx_mono_s = now_mono_s;
      impl_->imu = s;
      impl_->has_imu = true;
      ++impl_->imu_count;
      ++n;
    }
    if (rc > 0) dds_return_loan(impl_->imu_reader, raw, rc);
  }

  if (impl_->motion_reader > 0) {
    void* raw[1] = {nullptr};
    dds_sample_info_t info[1];
    const dds_return_t rc =
        dds_take(impl_->motion_reader, raw, info, 1, 1);
    if (rc > 0 && info[0].valid_data) {
      const drdds_msg_dds__MotionInfo_* m =
          static_cast<const drdds_msg_dds__MotionInfo_*>(raw[0]);
      MotionInfoSample s;
      s.vel_x = m->data.vel_x;
      s.vel_y = m->data.vel_y;
      s.vel_yaw = m->data.vel_yaw;
      s.height = m->data.height;
      s.payload = m->data.payload;
      s.remain_mile = m->data.remain_mile;
      s.motion_state = m->data.motion_state.state;
      s.gait = m->data.gait_state.gait;
      s.rx_mono_s = now_mono_s;
      impl_->motion = s;
      impl_->has_motion = true;
      ++impl_->motion_count;
      ++n;
    }
    if (rc > 0) dds_return_loan(impl_->motion_reader, raw, rc);
  }

  return n;
}

bool ChassisDds::latest_imu(ImuSample* out) const {
  if (!impl_ || !impl_->has_imu || out == nullptr) return false;
  *out = impl_->imu;
  return true;
}

bool ChassisDds::latest_motion_info(MotionInfoSample* out) const {
  if (!impl_ || !impl_->has_motion || out == nullptr) return false;
  *out = impl_->motion;
  return true;
}

double ChassisDds::imu_age_s(double now_mono_s) const {
  if (!impl_ || !impl_->has_imu) return -1.0;
  return now_mono_s - impl_->imu.rx_mono_s;
}

double ChassisDds::motion_info_age_s(double now_mono_s) const {
  if (!impl_ || !impl_->has_motion) return -1.0;
  return now_mono_s - impl_->motion.rx_mono_s;
}

int ChassisDds::actual_domain_id() const {
  if (!impl_ || impl_->participant <= 0) return -1;
  // Read BACK from the entity rather than echoed from the config. The two
  // differ exactly when something read an environment variable, which is the
  // failure DDS-9's self-report exists to make visible.
  dds_domainid_t id = 0;
  if (dds_get_domainid(impl_->participant, &id) != DDS_RETCODE_OK) return -1;
  return static_cast<int>(id);
}

std::uint64_t ChassisDds::imu_count() const {
  return impl_ ? impl_->imu_count : 0;
}
std::uint64_t ChassisDds::motion_info_count() const {
  return impl_ ? impl_->motion_count : 0;
}

}  // namespace quadruped
