#!/usr/bin/env python3
"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: gen_build_version.py
Brief: CHK-0-54 -- generate/verify xbrain/common/version/_build.py from git

Description:
Two modes, same source:
  --write   snapshot the CURRENT git state into _build.py (build-time step).
  --check   compare _build.py against the current git state; exit 1 on
            any field mismatch (CI drift gate). Never modifies the file.

Why this file rather than reading git at runtime. Runtime import of git
would (a) require the deployment root to carry .git, which we deliberately
strip when installing to /opt/xbrain_v6.versions/, and (b) turn a hash
error at bring-up (visible) into a silent "unknown" string. The generator
runs ONCE at build; the runtime just reads xbrain/common/version/_build.py.

Fields snapshotted:
  build_version    -- git describe --always --dirty (short SHA when no tag,
                      "...-dirty" suffix on uncommitted changes)
  commit_sha       -- full 40-char SHA, so a tag re-point can be told from
                      a re-generated build off a moved HEAD
  commit_date_iso  -- HEAD commit date in ISO 8601, so a log line carries
                      enough for `date -d` on the deployed machine
"""

import argparse
import ast
import os
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_TARGET = os.path.join(
    os.path.dirname(os.path.dirname(_HERE)),
    "xbrain", "common", "version", "_build.py",
)


def _git(*args, cwd=None):
    """Run git; return stripped stdout, raise CalledProcessError on nonzero."""
    return subprocess.check_output(("git",) + args, cwd=cwd,
                                   text=True, stderr=subprocess.STDOUT).strip()


def snapshot(cwd=None):
    """Read the three fields from the current git state, return a dict."""
    return {
        "build_version": _git("describe", "--always", "--dirty", cwd=cwd),
        "commit_sha": _git("rev-parse", "HEAD", cwd=cwd),
        "commit_date_iso": _git("log", "-1", "--format=%cI", "HEAD", cwd=cwd),
    }


def render(fields):
    """Return the exact bytes _build.py should contain for `fields`."""
    header = ('"""\n'
              'Copyright (c) 2026 Hachist Robotics\n'
              'Author: wanglei@hachist.com\n'
              '上海哈船智能船舶技术有限公司\n'
              'File: _build.py\n'
              'Brief: GENERATED by scripts/version/gen_build_version.py -- '
              'do not edit by hand\n'
              '\n'
              'Description:\n'
              'Committed snapshot of `git describe --always --dirty` + commit '
              'hash + commit\n'
              'ISO date at the moment scripts/version/gen_build_version.py '
              '--write last ran.\n'
              'CI drift gate: `python scripts/version/gen_build_version.py '
              '--check` refuses\n'
              'commit when this file disagrees with the current git state.\n'
              '\n'
              'Regenerate with:\n'
              '    python scripts/version/gen_build_version.py --write\n'
              '"""\n\n')
    body = "\n".join('%s = %r' % (k, v) for k, v in fields.items()) + "\n"
    return header + body


def read_committed(path):
    """Read the three fields back out of a committed _build.py by AST-parsing
    it -- more robust than importing (a syntactically broken file at least
    tells the caller which line, rather than raising ImportError deep in
    the loader)."""
    tree = ast.parse(open(path, encoding="utf-8").read())
    got = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name) \
                and isinstance(node.value, ast.Constant):
            got[node.targets[0].id] = node.value.value
    return got


def check(path, current):
    """Return list of (field, committed, current) triples where committed
    disagrees with current. Empty list = green."""
    if not os.path.exists(path):
        return [("<file>", None, "exists")]
    committed = read_committed(path)
    deltas = []
    for k, v in current.items():
        if committed.get(k) != v:
            deltas.append((k, committed.get(k), v))
    # Also flag EXTRA fields in the committed file we did not expect: a
    # generator upgrade that dropped a field would otherwise silently keep
    # the old value around.
    for k in committed:
        if k not in current:
            deltas.append((k, committed[k], None))
    return deltas


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    ap.add_argument("--target", default=DEFAULT_TARGET,
                    help="path to xbrain/common/version/_build.py")
    ap.add_argument("--cwd", default=None,
                    help="git working directory (default: parent of --target)")
    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--write", action="store_true",
                     help="snapshot current git state into --target")
    grp.add_argument("--check", action="store_true",
                     help="exit 1 if --target disagrees with current git state")
    args = ap.parse_args()

    try:
        current = snapshot(cwd=args.cwd)
    except subprocess.CalledProcessError as exc:
        # Fresh git or a clone with no HEAD (uncommon but real on partial
        # tarballs). Exit 1 loudly rather than write "unknown" -- the runtime
        # fallback is unknown-dev, and we do not want the generator to write
        # that string into the committed file (would look like it succeeded).
        print("FAIL: cannot read git state: %s" % exc)
        return 1

    if args.write:
        content = render(current)
        os.makedirs(os.path.dirname(args.target), exist_ok=True)
        with open(args.target, "w", encoding="utf-8") as fh:
            fh.write(content)
        print("WROTE %s" % args.target)
        for k, v in current.items():
            print("  %s = %r" % (k, v))
        return 0

    # --check
    deltas = check(args.target, current)
    if deltas:
        print("DRIFT: %s disagrees with current git state:" % args.target)
        for k, was, now in deltas:
            print("  %s: committed=%r current=%r" % (k, was, now))
        print("Regenerate with: python %s --write" % os.path.abspath(__file__))
        return 1
    print("OK: %s matches current git state" % args.target)
    for k, v in current.items():
        print("  %s = %r" % (k, v))
    return 0


if __name__ == "__main__":
    sys.exit(main())
