"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: query_engine.py
Brief: GWY-P4-15 -- query_templates.yaml + QT-1..QT-11 hard branches

Description:
16 S8.4 query answer templates. For queries with dynamic state
(e.g., 'battery level?' 'current mode?'), each template has 3
branches:

  ok       normal answer
  unknown  state is genuinely unknown (fresh boot, sensor missing)
  shadow   answer available but suspicious (e.g., stale reading)
  est      answer is an estimate (e.g., time-of-day approximate)

QT-1..QT-11 (16 S8.4): the 11 categories that MUST have all four
branches. Loading a template that has 'ok' but omits 'unknown' or
'shadow' branches -> refuse to load.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Dict, FrozenSet, List, Mapping


# 16 S8.2.1 QT-1..QT-11 -> 16 S8.4 template branch keys. KEY IS THE
# TEMPLATE NAME (query_light_state), NOT "QT-1_battery".
#
# 2026-08-11 (GWY-P4-34 / 32.B): the earlier table drifted badly from
# the doc -- it had QT-1=battery with ok/unknown/shadow branches, but
# 16 S8.2.1 QT-1 is G26 query_light_state (payload/chassis/all), QT-3 is
# G28 strobe (shadow-only, "per our record cannot read back"), QT-5 is
# G32 ptz_pose (unknown / unknown_moving, position readback is a fake
# value), etc. The eight-hard-branch table (16 S8.2.1) plus the S8.4
# template library are the authority; the branch keys below are the
# EXACT branch names from the S8.4 template blocks.
_QT_REQUIRED_BRANCHES: Dict[str, FrozenSet[str]] = {
    "query_light_state":    frozenset({"payload", "chassis", "all"}),      # QT-1/QT-2 G26
    "query_strobe_state":   frozenset({"shadow"}),                          # QT-3 G28
    "query_speaking":       frozenset({"idle", "speaking", "queued"}),      # QT-4 G30
    "query_ptz_pose":       frozenset({"unknown", "unknown_moving"}),       # QT-5 G32
    "query_ptz_zoom":       frozenset({"step_only"}),                       # QT-6 G33
    "query_ptz_owner":      frozenset({"held", "stale"}),                   # QT-7 G37
    "query_active_fence":   frozenset({"agree", "disagree"}),               # QT-8 G39
    "query_fence_relation": frozenset({"ok_in", "ok_out", "degraded"}),     # QT-9 G41
    "query_fence_detail":   frozenset({"ok", "timeout"}),                   # QT-11 G42
    # QT-10 G34 query_ptz_track has no multi-branch template in 16 S8.4
    # (it is "answer 'tracking' + target description"), so no required
    # branch set -- check_qt_branches no-ops for it, same as any
    # non-multi-branch query template.
}


class TemplateSchemaError(RuntimeError):
    """query_templates.yaml row missing a required branch."""


def check_qt_branches(template_id: str,
                      declared_branches: FrozenSet[str]) -> None:
    """Refuse if template_id is a QT-* category and its declared
    branches don't cover the required set."""
    req = _QT_REQUIRED_BRANCHES.get(template_id)
    if req is None:
        return    # not a QT template; no branch requirement here
    missing = req - declared_branches
    if missing:
        raise TemplateSchemaError(
            "QT template %s missing required branch(es) %s"
            % (template_id, sorted(missing)))


_PLACEHOLDER_RE = re.compile(r"\{([a-z_][a-z0-9_]*)\}")


def render_reply(
    templates: Mapping[str, Mapping[str, str]],
    template_name: str,
    branch: str,
    values: Mapping[str, Any],
) -> str:
    """GWY-P4-34 (32.B) executor. Fill one query-answer template.

    16 S8.2.1 CMD-40: the answer is generated by deterministic code from
    real state. This function does the LAST step -- take the template
    text for (template_name, branch) and substitute {placeholders} from
    `values`. It does NOT:
      * infer the branch (the CALLER picks ok/low/unknown/shadow from
        the state; e.g. QT-2 says {on_off} is decided by b7 ALONE, and
        that decision is the caller's, not this function's)
      * read the state topics (caller supplies `values`)
      * touch the LLM (16 S8.4 note 3: polish is off by default)

    Raises TemplateSchemaError on an unknown template / branch, or when a
    {placeholder} in the text has no value -- refusing to emit '{soc}'
    literally, which would be spoken aloud as a broken sentence.
    """
    tmpl = templates.get(template_name)
    if tmpl is None:
        raise TemplateSchemaError(
            "no query template named %r" % template_name)
    text = tmpl.get(branch)
    if text is None:
        raise TemplateSchemaError(
            "query template %r has no branch %r (has %s)"
            % (template_name, branch, sorted(tmpl)))
    needed = set(_PLACEHOLDER_RE.findall(text))
    have = set(values)
    missing = needed - have
    if missing:
        # A missing value would leave '{soc}' in the spoken text. That is
        # a silent-wrong answer (TTS reads the literal brace), worse than
        # a refusal -- so raise, do not ship a half-filled reply.
        raise TemplateSchemaError(
            "query template %r branch %r needs values %s but got %s"
            % (template_name, branch, sorted(needed), sorted(have)))
    out = text
    for k in needed:
        out = out.replace("{%s}" % k, str(values[k]))
    return out
