"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: test_gen_drift_gate.py
Brief: CHK-1-49 -- 守 scripts/ci/gen_drift_gate.py 与它的登记表

Description:
比对门本身也会腐烂, 而且腐烂方向最坏: 一个[登记表为空]的门跑起来是绿的,
输出"registry entries: 0", 看上去像通过. 所以本文件先钉住门的前提, 再钉
登记表的完备性.

*** 双向差集是判据变异体 (c) 打在的位置.
"把某个生成物从登记表里删掉" -- 门不会红(它只跑剩下的), 少的那一个从此
不受任何检查. 能抓住这件事的只有元测试: 磁盘上带 GENERATED 头注的文件集合
必须与登记表覆盖的集合[相等], 两个方向都查:
  * 磁盘有, 登记表没有 -> 新增生成物忘了登记(或有意不登记, 那就要进
    UNREGISTERED_BY_DESIGN 并写理由);
  * 登记表有, 磁盘没有 -> 生成物被删/改名, 登记表指着空气.

*** 一条有意的豁免: xbrain/common/version/_build.py.
构建戳的内容含 git describe 与构建时刻, 按定义不可重现. 把它放进逐字节
登记表会造出一条永远红的断言, 而永远红的断言最终会被人放宽到永远绿
(CLAUDE.md 3.2 形态2). 它归发版门(CHK-0-54)管. 本文件要求这类豁免必须
[逐条写在 UNREGISTERED_BY_DESIGN 里并带理由], 新增一条会红 -- 与
tests/meta 里守 NON_FAILURE 的那条同一个道理: 每多一个豁免口, 就多一个
藏真失败的地方.

Boundaries: 不判断生成物内容对不对(那是各生成器自己的 --check 与单测);
只保证[该被比对的都在被比对].
"""
from __future__ import annotations

import importlib.util
import pathlib
import re
import subprocess
import sys

import pytest

pytestmark = pytest.mark.no_device

ROOT = pathlib.Path(__file__).resolve().parents[2]
GATE = ROOT / "scripts" / "ci" / "gen_drift_gate.py"

#: 生成头注的形状: "GENERATED by <生成器路径>". 扫描面里只认这一种写法,
#: 所以新生成物必须照着写 -- 一个用别的措辞标注自己的生成物会被漏掉,
#: 这条约束由 test_registered_outputs_carry_the_marker 反向钉住.
_MARKER = re.compile(r"GENERATED by (\S+\.py)")

#: 扫描面. 显式列出而不是全仓走一遍: 全仓扫会把 docs/ 与本文件自己扫进去
#: (本文件正文里就有 GENERATED 这个词), 那是 CLAUDE.md 3.2 形态3 判据自伤.
_SCAN_DIRS = ("common/include", "xbrain", "common/enums")

#: 只看这些后缀 -- 生成物是代码, 不是文档.
_SCAN_SUFFIXES = (".h", ".hpp", ".py", ".cc")


def _gate():
    """按路径 import 比对门 -- 它是 script, 不是包."""
    spec = importlib.util.spec_from_file_location("gen_drift_gate", GATE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _marked_on_disk():
    """磁盘上自称由某个 .py 生成的文件(仓库相对路径)."""
    found = set()
    for rel_dir in _SCAN_DIRS:
        base = ROOT / rel_dir
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.suffix not in _SCAN_SUFFIXES or not path.is_file():
                continue
            # 只读头部: 标记在头注里, 而正文里出现这个词的多半是在讲别的事
            # (比如本项目的注释里常引用"生成物"这个概念).
            head = path.read_text(encoding="utf-8", errors="replace")[:2000]
            if _MARKER.search(head):
                found.add(str(path.relative_to(ROOT)))
    return found


def test_the_registry_is_not_empty():
    """*** 守本文件的前提, 也是这套门最容易退化成的样子.

    登记表为空时, 比对门跑起来输出 "registry entries: 0" 并 exit 0. 下面
    每条用例都会因为集合为空而空过. 一个门在什么都不检查的时候报绿, 正是
    CLAUDE.md 3.2 形态1.
    """
    assert len(_gate().REGISTRY) >= 3, "登记表至少应含判据点名的三条"


def test_gate_exits_zero_on_a_clean_tree():
    """基线: 未改动的工作树上比对门必须绿, 否则它会被当噪声关掉."""
    proc = subprocess.run([sys.executable, str(GATE)],
                          capture_output=True, text=True, cwd=str(ROOT))
    assert proc.returncode == 0, (
        "干净工作树上比对门就红了:\n%s%s" % (proc.stdout, proc.stderr))


def test_a_hand_edited_artifact_is_caught():
    """*** 判据变异体 (a): 手改 errors.h 加一个码, 必须红并打印该行.

    这是入库生成物真正的失效方式 -- 有人为了赶联调直接往头文件里加一个码,
    C++ 侧编译过了, 而 codes.yaml(单一真源)里没有它. 两侧闭集就此分叉.
    """
    gate = _gate()
    target = None
    for entry in gate.REGISTRY:
        if entry.mode == "render":
            target = ROOT / entry.outputs[0]
            break
    assert target is not None and target.is_file()
    original = target.read_text(encoding="utf-8")
    injected = original.replace(
        "#endif", 'constexpr const char* E_TOTALLY_MADE_UP = "E_X";\n#endif', 1)
    # 断言注入真的改了文件: 本仓踩过一次"变异体没生效, 看起来像断言失效".
    assert injected != original, "注入没有改动文件, 这次变异体不成立"
    try:
        target.write_text(injected, encoding="utf-8")
        proc = subprocess.run([sys.executable, str(GATE)],
                              capture_output=True, text=True, cwd=str(ROOT))
        assert proc.returncode != 0, "手改了生成物, 比对门却是绿的"
        assert "DRIFT" in proc.stdout
        # 要打出差异行, 不只是说"不一样"-- 读的人是为那一行来的.
        assert "E_TOTALLY_MADE_UP" in proc.stdout, (
            "报了漂移但没打出差异行:\n%s" % proc.stdout)
    finally:
        target.write_text(original, encoding="utf-8")


def test_registry_and_disk_agree_in_both_directions():
    """*** 判据变异体 (c): 从登记表里删掉一条, 这里必须红.

    比对门自己抓不到这件事 -- 它只跑登记表里有的. 少掉的那个生成物从此
    不受任何检查, 而且没有任何输出提示它不见了.
    """
    gate = _gate()
    registered = gate.registered_outputs()
    exempt = set(gate.UNREGISTERED_BY_DESIGN)
    on_disk = _marked_on_disk()
    missing_from_registry = sorted(on_disk - registered - exempt)
    assert not missing_from_registry, (
        "磁盘上带生成头注但没进登记表(也没写进豁免清单): %s"
        % missing_from_registry)
    stale = sorted(registered - on_disk)
    # 登记表里的路径必须真存在. 允许它没有 GENERATED 头注(whitelists.py
    # 就没有, 它是"与文档对齐"而非"整份渲染"), 但文件必须在.
    truly_gone = [rel for rel in stale if not (ROOT / rel).is_file()]
    assert not truly_gone, "登记表指向不存在的文件: %s" % truly_gone


def test_exemptions_are_listed_one_by_one_with_a_reason():
    """*** 豁免口必须小且说得出理由 -- 与 tests/meta 守 NON_FAILURE 同理.

    一条为了让门变绿而加进豁免清单的行, 测试套分辨不出来; 能分辨的只有
    复核的人, 前提是理由写在那里.
    """
    gate = _gate()
    assert len(gate.UNREGISTERED_BY_DESIGN) <= 3, (
        "豁免清单变长了 -- 每多一条就多一个不受检查的生成物, 需要复核")
    for rel, why in gate.UNREGISTERED_BY_DESIGN.items():
        assert (ROOT / rel).is_file(), (
            "%s 已不存在, 豁免比它的理由活得久了" % rel)
        assert len(why) > 20, "%s 的豁免理由太短, 半年后没人看得懂" % rel


def test_check_mode_entries_say_why_they_are_not_byte_compared():
    """判据要的是逐字节比对; 有一条做不到, 那就必须写清楚为什么.

    whitelists.py 的生成器不渲染整份文件, 只做集合语义比对. 不写理由的话,
    下一个人会以为这是偷懒, 然后去"补"一个渲染器 -- 那个渲染器会成为第二
    个真源.
    """
    for entry in _gate().REGISTRY:
        if entry.mode == "check":
            assert entry.why, "%s 走 check 模式却没写理由" % entry.generator


def test_registered_outputs_carry_the_marker_or_are_check_mode():
    """反向钉住头注写法: render 模式的生成物必须带 GENERATED by 标记.

    没有这条, 一个新生成物可以既在登记表里(所以门会比对它)又不带标记
    (所以双向差集看不见它) -- 那么下次它被人从登记表删掉时, 上面那条
    双向差集用例[不会红], 保护就是纸做的.
    """
    gate = _gate()
    on_disk = _marked_on_disk()
    for entry in gate.REGISTRY:
        if entry.mode != "render":
            continue
        for rel in entry.outputs:
            assert rel in on_disk, (
                "%s 由 render 模式登记, 却没有 GENERATED by 头注 -- "
                "双向差集看不见它" % rel)
