/*
 * Copyright (c) 2026 Hachist Robotics
 * Author: wanglei@hachist.com
 * 上海哈船智能船舶技术有限公司
 * File: test_chs_a_codec.cc
 * Brief: CHS-A codec against golden frames captured off the real chassis
 *
 * Description:
 * The golden vectors in test/golden/chs_a_frames.txt came off the wire on
 * 2026-09-15, not out of this encoder. That distinction is the whole point: a
 * vector generated by the code under test cannot disagree with it, so it would
 * prove only that the code equals itself (CLAUDE.md 3.2, form 1).
 *
 * What the cases pin, and what breaks in the field if they are removed:
 *   * the length field counts the ASDU ALONE -- get it wrong and the peer waits
 *     forever for bytes that already arrived, which looks like "the chassis
 *     stopped answering", not like a framing bug;
 *   * the codes go on the wire as DECIMAL -- a reviewer who "fixes" 1048676
 *     into "0x00100064" produces valid JSON that the chassis rejects with
 *     0xE002, and 13 S7.5 sends the reader looking at the encoder instead;
 *   * the PatrolDevice wrapper and the Time field are present -- the other two
 *     0xE002 causes, neither of them visible in the guide's field tables;
 *   * the five reserved header bytes are zero -- the vendor's own sample leaves
 *     them uninitialised (13 V-42), so "it worked once" says nothing;
 *   * a non-finite axis value is REFUSED rather than rendered -- "nan" is not
 *     JSON, and the frame would be our bug arriving as the chassis's error.
 *
 * The encoder is not asserted byte-identical to the captured TX frame: the Time
 * field carries the moment of capture, so the assertion is on structure and on
 * every field the protocol fixes. Where a byte-for-byte claim IS possible --
 * the header of a frame whose ASDU we reproduce exactly -- it is made.
 */

#include "quadruped/chs_a_codec.h"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <limits>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace quadruped::chs_a;  // NOLINT: test-local, keeps the cases readable

static int g_failures = 0;

#define CHECK(cond)                                                \
  do {                                                             \
    if (!(cond)) {                                                 \
      std::printf("FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond);  \
      ++g_failures;                                                \
    }                                                              \
  } while (0)

namespace {

std::vector<std::uint8_t> FromHex(const std::string& hex) {
  std::vector<std::uint8_t> out;
  out.reserve(hex.size() / 2);
  for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
    out.push_back(static_cast<std::uint8_t>(std::stoul(hex.substr(i, 2), nullptr, 16)));
  }
  return out;
}

// Load the golden file into tag -> bytes. A missing or empty file FAILS rather
// than yielding an empty map that would make every case below vacuously pass --
// the "zero tests ran, all green" shape.
std::map<std::string, std::vector<std::uint8_t>> LoadGolden(const std::string& path) {
  std::map<std::string, std::vector<std::uint8_t>> out;
  std::ifstream f(path);
  if (!f) {
    std::printf("FAIL cannot open golden file: %s\n", path.c_str());
    ++g_failures;
    return out;
  }
  std::string line;
  while (std::getline(f, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream is(line);
    std::string tag, hex;
    std::size_t n = 0;
    if (!(is >> tag >> n >> hex)) continue;
    std::vector<std::uint8_t> b = FromHex(hex);
    if (b.size() != n) {
      std::printf("FAIL golden %s: declared %zu bytes, hex holds %zu\n",
                  tag.c_str(), n, b.size());
      ++g_failures;
      continue;
    }
    out[tag] = std::move(b);
  }
  if (out.empty()) {
    std::printf("FAIL golden file parsed to zero vectors: %s\n", path.c_str());
    ++g_failures;
  }
  return out;
}

std::string AsduText(const std::vector<std::uint8_t>& frame) {
  if (frame.size() <= kHeaderBytes) return std::string();
  return std::string(reinterpret_cast<const char*>(frame.data() + kHeaderBytes),
                     frame.size() - kHeaderBytes);
}

bool Contains(const std::string& hay, const char* needle) {
  return hay.find(needle) != std::string::npos;
}

// A fixed instant so the rendered Time is deterministic: 2026-09-15 14:55:40
// local time on the machine that runs the test. Only the FORMAT is asserted,
// never the value, because the test must pass in any timezone.
constexpr std::int64_t kFixedWall = 1789455340;

// Poison byte. Every encode buffer is filled with it first, so a header field
// the encoder FAILS to write reads as 0xAA instead of whatever the stack
// happened to hold. Without this the "reserved bytes are zero" assertion
// passes on an encoder that never writes them -- found by mutation: deleting
// the memset left the test green because the stack was already zero.
constexpr std::uint8_t kPoison = 0xAA;

void Poison(std::uint8_t* buf, std::size_t cap) { std::memset(buf, kPoison, cap); }

// Structural invariants that hold for EVERY frame this encoder emits. Applied
// to all five commands: the mutation that drops the PatrolDevice wrapper from
// one encoder survived a test suite that only checked the wrapper on CAPTURED
// frames, because nothing looked at our own output that way.
void CheckFrameShape(const char* what, const std::uint8_t* buf, std::size_t n) {
  Header h;
  if (!ReadHeader(buf, n, &h)) {
    std::printf("FAIL %s: header did not parse\n", what);
    ++g_failures;
    return;
  }
  if (kHeaderBytes + h.asdu_len != n) {
    std::printf("FAIL %s: len field %u + 16 != %zu\n", what, h.asdu_len, n);
    ++g_failures;
  }
  if (h.format != kAsduFormatJson || h.version != kProtoVersion) {
    std::printf("FAIL %s: format/version byte wrong\n", what);
    ++g_failures;
  }
  // The five reserved bytes must be WRITTEN as zero, not merely happen to be.
  for (std::size_t i = 11; i < 16; ++i) {
    if (buf[i] != 0) {
      std::printf("FAIL %s: reserved byte %zu = 0x%02X (must be written zero)\n",
                  what, i, buf[i]);
      ++g_failures;
    }
  }
  const std::string body(reinterpret_cast<const char*>(buf + kHeaderBytes),
                         n - kHeaderBytes);
  // The three causes of 0xE002, checked on OUR output rather than only on the
  // chassis's: the wrapper, the mandatory Time, and an Items object.
  if (body.find("\"PatrolDevice\"") == std::string::npos) {
    std::printf("FAIL %s: missing the PatrolDevice wrapper\n", what);
    ++g_failures;
  }
  // The Time field must hold a rendered timestamp, not merely exist. The VALUE
  // is never asserted -- it is local time and the test must pass in any
  // timezone -- but the SHAPE is fixed by the guide as YYYY-MM-DD HH:MM:SS, and
  // a chassis that gets an empty string answers 0xE002 exactly as if the field
  // were absent. Checking only for the key let a mutant that rendered "" pass.
  const std::size_t tp = body.find("\"Time\": \"");
  if (tp == std::string::npos) {
    std::printf("FAIL %s: missing the mandatory Time field\n", what);
    ++g_failures;
  } else {
    const char* kShape = "dddd-dd-dd dd:dd:dd";  // d = one decimal digit
    const std::size_t v = tp + 9;                // just past the opening quote
    bool shape_ok = (v + 19 < body.size()) && body[v + 19] == '"';
    for (std::size_t i = 0; shape_ok && i < 19; ++i) {
      const char c = body[v + i];
      shape_ok = (kShape[i] == 'd') ? (c >= '0' && c <= '9') : (c == kShape[i]);
    }
    if (!shape_ok) {
      std::printf("FAIL %s: Time is not YYYY-MM-DD HH:MM:SS\n", what);
      ++g_failures;
    }
  }
  if (body.find("\"Items\"") == std::string::npos) {
    std::printf("FAIL %s: missing Items\n", what);
    ++g_failures;
  }
  // A truncated payload is still valid-looking bytes; the closing braces are
  // the cheapest proof the whole object was rendered.
  if (body.size() < 2 || body[body.size() - 1] != '}' ||
      body[body.size() - 2] != '}') {
    std::printf("FAIL %s: payload does not end with the two closing braces\n",
                what);
    ++g_failures;
  }
}

}  // namespace

int main(int argc, char** argv) {
  const std::string golden_path =
      (argc >= 2) ? argv[1] : "test/golden/chs_a_frames.txt";
  const auto golden = LoadGolden(golden_path);

  // ---- every captured frame parses as a header, with the invariants ------
  for (const auto& kv : golden) {
    const std::string& tag = kv.first;
    const std::vector<std::uint8_t>& f = kv.second;
    Header h;
    if (!ReadHeader(f.data(), f.size(), &h)) {
      std::printf("FAIL %s: header did not parse\n", tag.c_str());
      ++g_failures;
      continue;
    }
    // The length field counts the ASDU alone. This single assertion is the one
    // that would have caught the most likely framing mistake.
    if (kHeaderBytes + h.asdu_len != f.size()) {
      std::printf("FAIL %s: len field %u + 16 != %zu bytes on the wire\n",
                  tag.c_str(), h.asdu_len, f.size());
      ++g_failures;
    }
    CHECK(h.format == kAsduFormatJson);
    CHECK(h.version == kProtoVersion);
    // Reserved bytes: the sample code leaves them random, the field table says
    // zero, and the chassis accepted zero.
    for (std::size_t i = 11; i < 16; ++i) CHECK(f[i] == 0);
    // The wrapper and the mandatory Time field, in both directions.
    const std::string body = AsduText(f);
    CHECK(Contains(body, "\"PatrolDevice\""));
    CHECK(Contains(body, "\"Time\""));
    CHECK(Contains(body, "\"Items\""));
  }

  // ---- routing: the captured reports must resolve to the code book -------
  struct Expect {
    const char* tag;
    std::uint32_t type;
    std::uint32_t command;
  };
  const Expect expects[] = {
      {"RX_00100064_00000005", kHeartbeat.type, kHeartbeat.command},
      {"RX_00100001_00f00000", kTypeMotion, kReportCommand},
      {"RX_00100002_00f00000", kTypeDevice, kReportCommand},
      {"RX_00100064_00f00000", kTypeBasic, kReportCommand},
      {"RX_0010007f_00f00000", kTypeFault, kReportCommand},
      // The fifth report. 13 S7.1 v1.3 found it by measurement; it is
      // recognised so it can be dropped deliberately rather than counted as an
      // unknown frame and reported as a fault.
      {"RX_00100003_00f00000", kTypeLocationNav, kReportCommand},
  };
  for (const Expect& e : expects) {
    auto it = golden.find(e.tag);
    if (it == golden.end()) {
      std::printf("FAIL golden vector missing: %s\n", e.tag);
      ++g_failures;
      continue;
    }
    AsduRouting r;
    const bool ok = ParseAsduRouting(it->second.data() + kHeaderBytes,
                                     it->second.size() - kHeaderBytes, &r);
    if (!ok) {
      std::printf("FAIL %s: routing did not parse\n", e.tag);
      ++g_failures;
      continue;
    }
    CHECK(r.type == e.type);
    CHECK(r.command == e.command);
  }

  // ---- the generic response carries ErrorCode; a report does not ---------
  {
    auto ack = golden.find("RX_00100064_00000005");
    auto rep = golden.find("RX_00100064_00f00000");
    if (ack != golden.end() && rep != golden.end()) {
      AsduRouting a;
      AsduRouting b;
      CHECK(ParseAsduRouting(ack->second.data() + kHeaderBytes,
                             ack->second.size() - kHeaderBytes, &a));
      CHECK(ParseAsduRouting(rep->second.data() + kHeaderBytes,
                             rep->second.size() - kHeaderBytes, &b));
      // 0 means SUCCESS on this protocol, so "absent" and "zero" must never be
      // collapsed: a report read as a successful response would make a failed
      // command look acknowledged.
      CHECK(a.has_error_code == true);
      CHECK(a.error_code == 0u);
      CHECK(b.has_error_code == false);
    }
  }

  // ---- Time renders the instant it was GIVEN, not the fallback -----------
  {
    // The shape check in CheckFrameShape cannot see this on its own: when the
    // conversion fails, FormatTime substitutes "1970-01-01 00:00:00", which has
    // exactly the right shape. A mutant that broke strftime outright therefore
    // survived the whole suite -- the frames stayed well-formed and every one
    // of them was stamped with the epoch.
    //
    // Asserting the value is normally wrong here, because the field is LOCAL
    // time and the test must pass in any timezone. This prefix is the part that
    // is timezone-independent: kFixedWall is 2026-09-15 around 07:00 UTC, so
    // across the whole UTC-12..UTC+14 range the local date is the 14th or the
    // 15th of 2026-09. Any of those separates a real conversion from 1970.
    std::uint8_t buf[512];
    Poison(buf, sizeof(buf));
    const std::size_t n = EncodeHeartbeat(buf, sizeof(buf), 0, kFixedWall);
    CHECK(n > kHeaderBytes);
    const std::string body(reinterpret_cast<const char*>(buf + kHeaderBytes),
                           n - kHeaderBytes);
    CHECK(Contains(body, "\"Time\": \"2026-09-1"));
  }

  // ---- an unconvertible instant still yields a well-formed frame ----------
  {
    // The documented fallback (see FormatTime): on a conversion failure the
    // buffer must hold an obviously-wrong but well-formed timestamp, never
    // uninitialised stack. The difference matters because garbage is rejected
    // by the chassis with a loud 0xE002, whereas stack bytes parse sometimes
    // and not others -- an intermittent fault with no cause visible in a log.
    std::uint8_t buf[512];
    Poison(buf, sizeof(buf));
    const std::size_t n =
        EncodeHeartbeat(buf, sizeof(buf), 0, (std::numeric_limits<std::int64_t>::max)());
    CHECK(n > kHeaderBytes);
    CheckFrameShape("heartbeat/unconvertible-time", buf, n);
  }

  // ---- an ErrorCode that is PRESENT but unreadable is not code 0 ----------
  {
    // These ASDUs are written by hand rather than captured, and deliberately:
    // they are malformed input, so no chassis produces them. What is under test
    // is our rejection path, and a parser is only as good as its behaviour on
    // input it was not designed for.
    //
    // Why this matters more than it looks: 0 is SUCCESS on this protocol. A
    // parser that answers "code 0" when it merely failed to read the code turns
    // every unparseable failure report into an acknowledgement, and the caller
    // proceeds as though the command worked. The distinction has to be carried
    // in has_error_code, which is exactly why that flag exists.
    const char* bad[] = {
      // a string where a number belongs -- the shape a vendor firmware change
      // would most plausibly take
      "{\"PatrolDevice\": {\"Type\": 1048676, \"Command\": 5, "
      "\"Items\": {\"ErrorCode\": \"E008\"}}}",
      // present, with nothing after the colon
      "{\"PatrolDevice\": {\"Type\": 1048676, \"Command\": 5, "
      "\"Items\": {\"ErrorCode\":",
      // a negative number: not a valid code, must not be read as one
      "{\"PatrolDevice\": {\"Type\": 1048676, \"Command\": 5, "
      "\"Items\": {\"ErrorCode\": -1}}}",
    };
    for (const char* text : bad) {
      AsduRouting r;
      const bool ok = ParseAsduRouting(
          reinterpret_cast<const std::uint8_t*>(text), std::strlen(text), &r);
      // Routing itself still succeeds -- Type and Command are readable, and the
      // frame must still be routed. It is only the code that is unknown.
      CHECK(ok);
      if (ok) {
        CHECK(r.type == 1048676u);
        CHECK(r.has_error_code == false);
      }
    }
  }

  // ---- our heartbeat reproduces the captured shape ------------------------
  {
    std::uint8_t buf[512];
    Poison(buf, sizeof(buf));
    const std::size_t n = EncodeHeartbeat(buf, sizeof(buf), 0, kFixedWall);
    CHECK(n > kHeaderBytes);
    CheckFrameShape("heartbeat", buf, n);
    Header h;
    CHECK(ReadHeader(buf, n, &h));
    CHECK(kHeaderBytes + h.asdu_len == n);
    CHECK(h.msg_id == 0);
    const std::string body(reinterpret_cast<const char*>(buf + kHeaderBytes),
                           n - kHeaderBytes);
    // DECIMAL codes. If this ever reads 0x00100064 the chassis answers 0xE002.
    CHECK(Contains(body, "\"Type\": 1048676"));
    CHECK(Contains(body, "\"Command\": 5"));
    CHECK(Contains(body, "\"Items\": {}"));
    // Time format, not Time value: the test must pass in any timezone.
    const std::size_t tpos = body.find("\"Time\": \"");
    CHECK(tpos != std::string::npos);
    if (tpos != std::string::npos) {
      const std::string ts = body.substr(tpos + 9, 19);
      CHECK(ts.size() == 19);
      CHECK(ts[4] == '-' && ts[7] == '-' && ts[10] == ' ' && ts[13] == ':' &&
            ts[16] == ':');
    }
    // The header of our frame is byte-identical to the captured one except for
    // the length: same sync, same format, same version, same zeroed reserve.
    auto tx = golden.find("TX_heartbeat");
    if (tx != golden.end()) {
      const std::vector<std::uint8_t>& g = tx->second;
      CHECK(std::memcmp(buf, g.data(), 4) == 0);   // sync word
      CHECK(buf[8] == g[8] && buf[9] == g[9] && buf[10] == g[10]);
      CHECK(std::memcmp(buf + 11, g.data() + 11, 5) == 0);  // reserved
      // Same ASDU length: the payload differs only in the Time VALUE, which is
      // fixed-width, so a length difference means a structural difference.
      CHECK(h.asdu_len == static_cast<std::uint16_t>(g.size() - kHeaderBytes));
    }
  }

  // ---- the command encoders ----------------------------------------------
  {
    std::uint8_t buf[512];
    Poison(buf, sizeof(buf));
    std::size_t n = EncodeMotionState(buf, sizeof(buf), 7, kFixedWall, 1);
    CHECK(n > 0);
    CheckFrameShape("motion_state", buf, n);
    std::string body(reinterpret_cast<const char*>(buf + kHeaderBytes),
                     n - kHeaderBytes);
    CHECK(Contains(body, "\"Type\": 1048577"));    // 0x00100001
    CHECK(Contains(body, "\"Command\": 2097154"));  // 0x00200002
    CHECK(Contains(body, "\"MotionParam\": 1"));
    Header h;
    CHECK(ReadHeader(buf, n, &h));
    CHECK(h.msg_id == 7);  // the pairing id the chassis echoes

    Poison(buf, sizeof(buf));
    n = EncodeUsageMode(buf, sizeof(buf), 1, kFixedWall, 1);
    CheckFrameShape("usage_mode", buf, n);
    body.assign(reinterpret_cast<const char*>(buf + kHeaderBytes), n - kHeaderBytes);
    CHECK(Contains(body, "\"Type\": 1048578"));    // 0x00100002
    CHECK(Contains(body, "\"Command\": 5242882"));  // 0x00500002
    CHECK(Contains(body, "\"Mode\": 1"));

    Poison(buf, sizeof(buf));
    n = EncodeGait(buf, sizeof(buf), 2, kFixedWall, 0x3002u);
    CheckFrameShape("gait", buf, n);
    body.assign(reinterpret_cast<const char*>(buf + kHeaderBytes), n - kHeaderBytes);
    CHECK(Contains(body, "\"Command\": 3145730"));  // 0x00300002
    CHECK(Contains(body, "\"GaitParam\": 12290"));  // 0x3002 in decimal
    // ActionParam is deliberately absent (13 V-45: its value table does not
    // exist, so a guessed value would be invented data).
    CHECK(!Contains(body, "ActionParam"));

    Poison(buf, sizeof(buf));
    n = EncodeSdkMode(buf, sizeof(buf), 3, kFixedWall, true, 100);
    CheckFrameShape("sdk_mode", buf, n);
    body.assign(reinterpret_cast<const char*>(buf + kHeaderBytes), n - kHeaderBytes);
    CHECK(Contains(body, "\"SDKEnable\": true"));
    CHECK(Contains(body, "\"Frequency\": 100"));
  }

  // ---- the axis command, including the refusal that matters --------------
  {
    std::uint8_t buf[512];
    Poison(buf, sizeof(buf));
    AxisCommand c;
    c.vx = 0.25;
    c.yaw = -0.5;
    std::size_t n = EncodeRealAxis(buf, sizeof(buf), 9, kFixedWall, c);
    CHECK(n > 0);
    CheckFrameShape("real_axis", buf, n);
    const std::string body(reinterpret_cast<const char*>(buf + kHeaderBytes),
                           n - kHeaderBytes);
    CHECK(Contains(body, "\"Command\": 1114114"));  // 0x00110002, the REAL axis
    CHECK(Contains(body, "\"X\": 0.250000"));
    CHECK(Contains(body, "\"Yaw\": -0.500000"));
    // All six axes present even when zero: the chassis reads the object, and a
    // missing field is not the same as a zero one.
    CHECK(Contains(body, "\"Y\": 0.000000"));
    CHECK(Contains(body, "\"Z\": 0.000000"));
    CHECK(Contains(body, "\"Roll\": 0.000000"));
    CHECK(Contains(body, "\"Pitch\": 0.000000"));

    // *** The refusal. "nan" is not JSON; letting it out would arrive as
    // 0xE002 and be misread as a chassis fault.
    AxisCommand bad;
    bad.vx = std::nan("");
    CHECK(EncodeRealAxis(buf, sizeof(buf), 10, kFixedWall, bad) == 0);
    AxisCommand inf;
    inf.yaw = std::numeric_limits<double>::infinity();
    CHECK(EncodeRealAxis(buf, sizeof(buf), 11, kFixedWall, inf) == 0);
  }

  // ---- a too-small buffer returns 0, never a truncated frame -------------
  {
    std::uint8_t tiny[20];
    CHECK(EncodeHeartbeat(tiny, sizeof(tiny), 0, kFixedWall) == 0);
    CHECK(EncodeHeartbeat(nullptr, 512, 0, kFixedWall) == 0);
    // Exactly the header size: there is room for a header and nothing else, so
    // a partial frame is the tempting wrong answer.
    std::uint8_t exact[kHeaderBytes];
    CHECK(EncodeHeartbeat(exact, sizeof(exact), 0, kFixedWall) == 0);
  }

  // ---- routing refuses what it cannot read -------------------------------
  {
    AsduRouting r;
    const char* not_ours = "{\"Other\": {\"Type\": 1, \"Command\": 2}}";
    CHECK(!ParseAsduRouting(reinterpret_cast<const std::uint8_t*>(not_ours),
                            std::strlen(not_ours), &r));
    const char* no_cmd = "{\"PatrolDevice\": {\"Type\": 1048676}}";
    CHECK(!ParseAsduRouting(reinterpret_cast<const std::uint8_t*>(no_cmd),
                            std::strlen(no_cmd), &r));
    // A Type holding an object rather than a number must be refused, not read
    // as 0 -- 0 is a legal-looking code.
    const char* obj = "{\"PatrolDevice\": {\"Type\": {}, \"Command\": 5}}";
    CHECK(!ParseAsduRouting(reinterpret_cast<const std::uint8_t*>(obj),
                            std::strlen(obj), &r));
  }

  // ---- C-07 custom light (13 S5.1 / vendor guide 1.2.7) ------------------
  {
    // The two lamps are POSITIONAL: Led[0] head, Led[1] tail. Swapping them
    // produces a frame the chassis accepts and acts on backwards, which is
    // why the two are given different values in every field -- a test with
    // matching lamps passes on a swapped encoder.
    std::uint8_t buf[512];
    LedSetting head;
    head.pattern = 5;          // blink
    head.color = 1;            // white
    head.cycle_s = 1;
    LedSetting tail;
    tail.pattern = 4;          // breath
    tail.color = 2;            // green
    tail.cycle_s = 2;
    const std::size_t n = EncodeCustomLight(buf, sizeof(buf), 0x1234,
                                                   kFixedWall, true, head, tail);
    CHECK(n > kHeaderBytes);
    Header h;
    CHECK(ReadHeader(buf, n, &h));
    const std::string asdu(reinterpret_cast<const char*>(buf) +
                               kHeaderBytes,
                           n - kHeaderBytes);
    // CLAUDE.md 5.5: hex32 codes go out as DECIMAL integers -- JSON has no
    // hexadecimal literal, and a frame that spells them in hex comes back
    // 0xE002 on the first try.
    CHECK(asdu.find("\"Type\": 1048581") != std::string::npos);    // 0x00100005
    CHECK(asdu.find("\"Command\": 2097154") != std::string::npos); // 0x00200002
    CHECK(asdu.find("\"PatrolDevice\"") != std::string::npos);
    CHECK(asdu.find("\"Time\"") != std::string::npos);
    CHECK(asdu.find("\"CustomMode\": true") != std::string::npos);
    // Color is an ARRAY on the wire even though 11 S9.4.1 names one colour;
    // the vendor's own example sends a single-element array.
    const std::size_t head_at = asdu.find("\"Color\": [1]");
    const std::size_t tail_at = asdu.find("\"Color\": [2]");
    CHECK(head_at != std::string::npos);
    CHECK(tail_at != std::string::npos);
    // ORDER. mutant: swap head and tail in the encoder -> this goes red while
    // every "the field is present" check above stays green.
    CHECK(head_at < tail_at);
    CHECK(asdu.find("\"Type\": 5") < asdu.find("\"Type\": 4"));
    CHECK(asdu.find("\"Cycle\": 1") < asdu.find("\"Cycle\": 2"));
  }
  {
    // CustomMode false still sends both lamps: the message has no form that
    // omits them, and leaving them out would let the chassis decide.
    std::uint8_t buf[512];
    LedSetting off;
    const std::size_t n = EncodeCustomLight(buf, sizeof(buf), 1, kFixedWall,
                                                   false, off, off);
    CHECK(n > kHeaderBytes);
    const std::string asdu(reinterpret_cast<const char*>(buf) +
                               kHeaderBytes,
                           n - kHeaderBytes);
    CHECK(asdu.find("\"CustomMode\": false") != std::string::npos);
    CHECK(asdu.find("\"Led\": [") != std::string::npos);
  }

  if (g_failures == 0) {
    std::printf("ALL CHS_A_CODEC TESTS PASSED\n");
    return 0;
  }
  std::printf("%d CHS_A_CODEC TEST(S) FAILED\n", g_failures);
  return 1;
}
