#!/usr/bin/env python3
"""
Copyright (c) 2026 Hachist Robotics
Author: wanglei@hachist.com
上海哈船智能船舶技术有限公司
File: gen_digest_golden.py
Brief: Emit the CFG-CM-10 golden vectors, with the canonical string written by hand

Description:
What problem this solves. A golden vector file generated by running the
implementation over some inputs proves nothing: it says the implementation agrees
with itself, and it will happily bless a bug the moment it is regenerated. That
is CLAUDE.md 3.2 form 7 -- a definition dressed up as a measurement.

So the canonical string of every vector here is written out BY HAND from the two
sections (10 S5.4.4 and 11 S9A.2), and this script does only the part a human
cannot do reliably: apply sha256 or crc32 to it. Before emitting anything it
checks each hand-written string against what the implementation actually
produces, and refuses to write the file on any mismatch. Which of the two is
wrong is then a question for a person, and that is the point -- the disagreement
surfaces here rather than being papered over by regeneration.

Consequence worth stating: this script FAILING is the normal way a real defect in
the serialiser announces itself. Do not fix a failure by copying the
implementation output into the expected field.

Run:
  python3 scripts/gen_digest_golden.py
Writes:
  tests/common/golden/common_digest_vectors.json
  tests/common/golden/fence_crc32_vectors.json
"""

import binascii
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from xbrain.common.digest import canonical_fence_string, canonical_json  # noqa: E402

GOLDEN_DIR = os.path.join(ROOT, "tests", "common", "golden")

# -- common_digest vectors ----------------------------------------------------
#
# Each entry states the tree, the canonical string it must serialise to, and why
# the vector exists. The "why" is not decoration: a vector nobody can explain is
# a vector nobody dares change when the rules move.

COMMON_VECTORS = [
    {
        "name": "empty",
        "why": "A tree with no common section still has a defined digest. "
               "take_common_subtree returns {} rather than raising, so this is "
               "the value that pins down what {} hashes to.",
        "tree": {},
        "canonical": "{}",
    },
    {
        "name": "key_order_is_not_insertion_order",
        "why": "Keys are inserted z, a, m and must come out a, m, z. A "
               "serialiser that forgot to sort would pass every single-key "
               "vector and fail only here.",
        "tree": {"common": {"z": 1, "a": 2, "m": 3}},
        "canonical": '{"a":2,"m":3,"z":1}',
    },
    {
        "name": "key_order_above_the_bmp",
        "why": "*** Read this before trusting the TODO's mutation 1. UTF-8 is "
               "order-preserving: sorting by UTF-8 BYTES and sorting by Unicode "
               "CODE POINT give the same answer for every pair of strings, "
               "always. So 'change the sort to code point order' cannot turn "
               "anything red in Python, and claiming it was run would be a "
               "measurement nobody could have made. The ordering that really "
               "differs is UTF-16 CODE UNIT order, which is what a Java, "
               "JavaScript or Windows-wstring reimplementation produces: "
               "U+10400 encodes to the surrogate pair D801 DC00, and 0xD801 < "
               "0xFF21, so under UTF-16 the Deseret key sorts BEFORE the "
               "fullwidth A, while under bytes and code points it sorts after. "
               "These three keys are chosen so that the two orderings disagree, "
               "and test_digest.py runs that substituted mutation.",
        "tree": {"common": {"é": 1, "Ａ": 2, "\U00010400": 3}},
        "canonical": '{"é":1,"Ａ":2,"\U00010400":3}',
    },
    {
        "name": "no_whitespace_anywhere",
        "why": "json.dumps defaults to ', ' and ': ' separators. This vector is "
               "nested two deep so a stray space would appear more than once.",
        "tree": {"common": {"a": {"b": [1, 2]}, "c": "d"}},
        "canonical": '{"a":{"b":[1,2]},"c":"d"}',
    },
    {
        "name": "non_ascii_is_not_escaped",
        "why": "json.dumps defaults to ensure_ascii=True and would write "
               "\\u573a\\u533a here. The rule says UTF-8 direct.",
        "tree": {"common": {"site": "场区"}},
        "canonical": '{"site":"场区"}',
    },
    {
        "name": "integers_carry_no_decimal_point",
        "why": "3 must be '3'. A serialiser routing everything through the "
               "float path would write '3.0' and no golden vector using only "
               "fractional values would catch it.",
        "tree": {"common": {"n": 3}},
        "canonical": '{"n":3}',
    },
    {
        "name": "integral_float_matches_the_integer",
        "why": "2.0 and 2 must serialise the same. A YAML loader returning one "
               "where another returns the other must not move the digest -- and "
               "on the C++ side these are genuinely different types.",
        "tree": {"common": {"n": 2.0}},
        "canonical": '{"n":2}',
    },
    {
        "name": "float_trailing_zeros_stripped",
        "why": "2.50 must be '2.5'. Pins the 'strip trailing zeros' half of the "
               "float rule, which %.17g alone does not always do.",
        "tree": {"common": {"a_mps2": 2.50, "half": 0.5}},
        "canonical": '{"a_mps2":2.5,"half":0.5}',
    },
    {
        "name": "float_needing_all_17_digits",
        "why": "0.1 has no exact double. %.17g gives 0.10000000000000001 and a "
               "shorter format would give 0.1 -- both are the same double, and "
               "the two languages must pick the SAME one of them.",
        "tree": {"common": {"eps": 0.1}},
        "canonical": '{"eps":0.10000000000000001}',
    },
    {
        "name": "list_order_is_preserved",
        "why": "R-5: a list is replaced whole and its order is semantic. A "
               "serialiser sorting list elements alongside map keys would pass "
               "every scalar vector.",
        "tree": {"common": {"bands": ["c", "a", "b"]}},
        "canonical": '{"bands":["c","a","b"]}',
    },
    {
        "name": "null_stays_null",
        "why": "An unassigned safety parameter is written null per CLAUDE.md "
               "3.1. It must reach the digest as null and not vanish, otherwise "
               "assigning a value later would not move the digest.",
        "tree": {"common": {"safety": {"brake_a_mps2": None}}},
        "canonical": '{"safety":{"brake_a_mps2":null}}',
    },
    {
        "name": "bool_is_not_an_integer",
        "why": "In Python bool subclasses int, so an unguarded int check writes "
               "true as 1. In C++ the two are unrelated types and it writes "
               "true. Nothing but a vector catches this.",
        "tree": {"common": {"on": True, "off": False, "one": 1}},
        "canonical": '{"off":false,"on":true,"one":1}',
    },
    {
        "name": "private_sections_are_excluded",
        "why": "*** The 'only common.*' rule. Same common subtree as the "
               "key-order vector, plus two process-private sections; the digest "
               "must be identical to that vector's. A private edit must not "
               "block release.",
        "tree": {"common": {"z": 1, "a": 2, "m": 3},
                 "p1_motion": {"loop_hz": 20},
                 "p5_gateway": {"port": 8080}},
        "canonical": '{"a":2,"m":3,"z":1}',
    },
    {
        "name": "realistic_common_fragment",
        "why": "A fragment shaped like the real common.* -- nested maps, a list "
               "of maps, mixed number types, a null. Present so the vector set "
               "is not made only of one-feature cases, which is how an "
               "interaction between two rules gets missed. *** Note the lat and "
               "lon: 35.011 the double is 35.011000000000003 at seventeen "
               "significant digits, and that is what %.17g must print. The "
               "hand-written string here originally read 35.011 and this script "
               "rejected it, which is the check working as intended -- an "
               "implementation shortening it to 35.011 would round-trip fine in "
               "Python and disagree with C++ on the very first real "
               "configuration, since enu_origin is always a WGS84 degree.",
        "tree": {"common": {
            "spec": {"v_max_mps": 2.0, "a_brake_mps2": None},
            "geo": {"enu_origin": {"lat": 35.011, "lon": 135.091, "alt_m": 12}},
            "motion": {"profiles": [
                {"name": "patrol", "v": 2.0},
                {"name": "approach", "v": 0.5},
            ]},
            "qos": {"bindings": ["rt/**", "gen/**"]},
        }},
        "canonical": (
            '{"geo":{"enu_origin":{"alt_m":12,"lat":35.011000000000003,'
            '"lon":135.09100000000001}},'
            '"motion":{"profiles":[{"name":"patrol","v":2},'
            '{"name":"approach","v":0.5}]},'
            '"qos":{"bindings":["rt/**","gen/**"]},'
            '"spec":{"a_brake_mps2":null,"v_max_mps":2}}'
        ),
    },
]

# -- fence crc32 vectors ------------------------------------------------------

_TRIANGLE = [{"lat": 35.011, "lon": 135.091},
             {"lat": 35.0112, "lon": 135.0935},
             {"lat": 35.0095, "lon": 135.0938}]

FENCE_VECTORS = [
    {
        "name": "single_allow_polygon",
        "why": "The base case: one allow polygon, three vertices. Everything "
               "below is a one-field change away from this, so its canonical "
               "string is the one to read first.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 7,
            "polygons": [{
                "poly_id": "f-yard", "role": "allow", "name": "yard outline",
                "priority": 0, "winding": "ccw", "hard_enforce": True,
                "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|7|"
            "f-yard|allow|ccw|1|0||"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "name_is_not_in_the_recipe",
        "why": "Same fence, different human name. The crc32 must be UNCHANGED: "
               "S9A.2 keeps name out so a pure HMI rename does not trigger a "
               "stage/commit across the whole stack.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 7,
            "polygons": [{
                "poly_id": "f-yard", "role": "allow", "name": "RENAMED",
                "priority": 0, "winding": "ccw", "hard_enforce": True,
                "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|7|"
            "f-yard|allow|ccw|1|0||"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "speed_limit_polygon_carries_its_limit",
        "why": "*** role=speed_limit is the one role whose limit enters the "
               "string, as %.3f. The v0.2 recipe omitted it, so lowering a slow "
               "zone produced an identical crc32 -- the change did not take "
               "effect and nothing reported an error.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 8,
            "polygons": [{
                "poly_id": "f-yard_slow", "role": "speed_limit",
                "name": "slow zone", "priority": 0, "winding": "ccw",
                "hard_enforce": False, "speed_limit_mps": 1.0,
                "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|8|"
            "f-yard_slow|speed_limit|ccw|0|0|1.000|"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "lowered_speed_limit_changes_the_crc",
        "why": "*** The pair to the vector above: identical geometry, limit "
               "1.0 -> 0.5. Two vectors that must differ, which is the only "
               "shape that can catch a recipe silently dropping the field.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 8,
            "polygons": [{
                "poly_id": "f-yard_slow", "role": "speed_limit",
                "name": "slow zone", "priority": 0, "winding": "ccw",
                "hard_enforce": False, "speed_limit_mps": 0.5,
                "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|8|"
            "f-yard_slow|speed_limit|ccw|0|0|0.500|"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "non_speed_limit_role_writes_an_empty_field",
        "why": "A zone polygon that happens to carry speed_limit_mps. S9A.2 "
               "makes the field required only for speed_limit, so the stray "
               "value is legal input and must NOT enter the string. The field "
               "is empty, not zero -- zero would collide with a real 0.000.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 9,
            "polygons": [{
                "poly_id": "f-gate_post", "role": "zone", "name": "gate post",
                "priority": 0, "winding": "ccw", "hard_enforce": False,
                "speed_limit_mps": 9.9, "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|9|"
            "f-gate_post|zone|ccw|0|0||"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "two_polygons_stacking_order_a",
        "why": "*** Mutation 2 in the TODO. Two forbid polygons, priorities 10 "
               "and 20. Paired with the vector below, which swaps only the two "
               "priority values.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 11,
            "polygons": [
                {"poly_id": "f-fuel", "role": "forbid", "priority": 10,
                 "winding": "cw", "hard_enforce": True, "vertices": _TRIANGLE},
                {"poly_id": "f-tower", "role": "forbid", "priority": 20,
                 "winding": "cw", "hard_enforce": True, "vertices": _TRIANGLE},
            ],
        },
        "canonical": (
            "yard_main|11|"
            "f-fuel|forbid|cw|1|10||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
            "f-tower|forbid|cw|1|20||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "two_polygons_stacking_order_b",
        "why": "*** The pair: same two polygons, priorities swapped to 20 and "
               "10. Painter-algorithm order decides which of two overlapping "
               "constraints wins, so the crc32 must differ. Drop priority from "
               "the recipe and these two collide.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 11,
            "polygons": [
                {"poly_id": "f-fuel", "role": "forbid", "priority": 20,
                 "winding": "cw", "hard_enforce": True, "vertices": _TRIANGLE},
                {"poly_id": "f-tower", "role": "forbid", "priority": 10,
                 "winding": "cw", "hard_enforce": True, "vertices": _TRIANGLE},
            ],
        },
        "canonical": (
            "yard_main|11|"
            "f-fuel|forbid|cw|1|20||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
            "f-tower|forbid|cw|1|10||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "negative_priority_keeps_its_sign",
        "why": "The recipe says 'sign kept'. int32 admits negatives and a "
               "formatter using an unsigned conversion would turn -5 into a "
               "very large positive number without complaining.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 12,
            "polygons": [{
                "poly_id": "f-base", "role": "allow", "priority": -5,
                "winding": "ccw", "hard_enforce": True, "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|12|"
            "f-base|allow|ccw|1|-5||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "hard_enforce_false_writes_zero",
        "why": "'0', not 'false'. A C++ stream renders a bool as 1/0 and a text "
               "formatter renders it as true/false; the section settles it and "
               "this vector is what holds both languages to the choice.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 13,
            "polygons": [{
                "poly_id": "f-soft", "role": "forbid", "priority": 0,
                "winding": "cw", "hard_enforce": False, "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|13|"
            "f-soft|forbid|cw|0|0||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
    {
        "name": "vertex_order_is_not_sorted",
        "why": "Same three vertices as the base case, rotated. Winding is what "
               "tells inside from outside, so a recipe that sorted vertices "
               "would make these two collide -- and would make one fence the "
               "inverse of the other while reporting them identical.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 7,
            "polygons": [{
                "poly_id": "f-yard", "role": "allow", "priority": 0,
                "winding": "ccw", "hard_enforce": True,
                "vertices": [_TRIANGLE[2], _TRIANGLE[0], _TRIANGLE[1]],
            }],
        },
        "canonical": (
            "yard_main|7|"
            "f-yard|allow|ccw|1|0||"
            "35.00950000,135.09380000;"
            "35.01100000,135.09100000;"
            "35.01120000,135.09350000;"
        ),
    },
    {
        "name": "rev_bump_changes_the_crc",
        "why": "The base case with rev 7 -> 8 and nothing else touched. S-5 "
               "keys idempotency on fence_set_id + rev + crc32, so a recipe "
               "leaving rev out would let a bumped revision look like a "
               "duplicate commit.",
        "fence": {
            "fence_set_id": "yard_main", "rev": 8,
            "polygons": [{
                "poly_id": "f-yard", "role": "allow", "priority": 0,
                "winding": "ccw", "hard_enforce": True, "vertices": _TRIANGLE,
            }],
        },
        "canonical": (
            "yard_main|8|"
            "f-yard|allow|ccw|1|0||"
            "35.01100000,135.09100000;35.01120000,135.09350000;"
            "35.00950000,135.09380000;"
        ),
    },
]


def check_and_stamp(vectors, builder, hasher, label):
    """Verify every hand-written canonical string, then stamp its hash.

    The order matters. Building the hash first and comparing afterwards would
    still detect a mismatch, but the natural fix when a hash differs is to
    accept the new one -- so the string comparison is what this reports, and the
    hash is only ever derived from the string a human wrote.
    """
    out = []
    for vec in vectors:
        produced = builder(vec)
        if produced != vec["canonical"]:
            print("MISMATCH in %s vector %r" % (label, vec["name"]))
            print("  hand-written: %r" % vec["canonical"])
            print("  implementation: %r" % produced)
            print("")
            print("  Do NOT resolve this by copying the implementation output")
            print("  into the expected field. One of the two is wrong and which")
            print("  one is a question for a person, not for this script.")
            return None
        entry = dict(vec)
        entry["expected"] = hasher(vec["canonical"])
        out.append(entry)
    return out


def main():
    os.makedirs(GOLDEN_DIR, exist_ok=True)

    common = check_and_stamp(
        COMMON_VECTORS,
        lambda v: canonical_json(v["tree"].get("common", {})),
        lambda s: hashlib.sha256(s.encode("utf-8")).hexdigest()[:16],
        "common_digest")
    fence = check_and_stamp(
        FENCE_VECTORS,
        lambda v: canonical_fence_string(v["fence"]),
        lambda s: "%08x" % (binascii.crc32(s.encode("utf-8")) & 0xFFFFFFFF),
        "fence_crc32")
    if common is None or fence is None:
        return 1

    # A collision between two vectors that are supposed to differ would make the
    # whole set weaker without failing anything, so it is checked here rather
    # than left to the reader.
    for name, vecs, key in (("common_digest", common, "canonical"),
                            ("fence_crc32", fence, "canonical")):
        seen = {}
        for v in vecs:
            seen.setdefault(v[key], []).append(v["name"])
        for text, names in seen.items():
            if len(names) > 1:
                print("note: %s vectors %s share a canonical string; that is "
                      "intended only where the vector says so" % (name, names))

    for filename, payload, section in (
            ("common_digest_vectors.json", common, "10 S5.4.4"),
            ("fence_crc32_vectors.json", fence, "11 S9A.2")):
        path = os.path.join(GOLDEN_DIR, filename)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump({"section": section,
                       "generated_by": "scripts/gen_digest_golden.py",
                       "note": "canonical strings are hand-written from the "
                               "section; only the hash is computed. Do not "
                               "regenerate to make a failing test pass.",
                       "vectors": payload}, fh,
                      ensure_ascii=False, indent=2, sort_keys=False)
            fh.write("\n")
        print("wrote %s (%d vectors)" % (path, len(payload)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
