/*
 * Copyright (c) 2026 Hachist Robotics
 * Author: wanglei@hachist.com
 * 上海哈船智能船舶技术有限公司
 * File: closed_sets.h
 * Brief: C++17 view of the non-error closed sets, byte-equal to the Python export
 *
 * Description:
 * GENERATED by scripts/gen/closed_sets_h.py from xbrain/common/enums/sets.yaml.
 * Do not edit by hand. A hand edit is reverted by the next regeneration, and
 * until then the two languages disagree about a closed set -- which compiles,
 * runs, and surfaces only during integration, when a peer branches on a value
 * this side spells differently. tests/common/test_closed_sets.py fails on any
 * difference between this file and a fresh render.
 *
 * Why it exists. chassis_relay, quadruped, perception and rtk_driver need the
 * same closed sets the Python processes use, and CLAUDE.md 5.3 forbids anything
 * under common/ from depending on rclcpp or any ROS type -- chassis_relay is on
 * the emergency-stop path under CRL-4 and CRL-5, and could not use this library
 * otherwise. Nothing below leaves the C++17 standard library.
 *
 * Where the values come from. sets.yaml is the single source of truth and is
 * bound to the design volumes by a symmetric-difference metatest, one case per
 * set. That metatest is what establishes the values are RIGHT; the drift check
 * on this file only establishes that nobody edited the copy. The two are
 * separate claims on purpose: comparing a generated artifact with its own
 * generator is true by construction and would prove nothing.
 *
 * What this header does NOT do:
 *   * it does not throw. The Python side raises ClosedSetViolation. Here the
 *     nearest consumer runs under CRL-4, which forbids dynamic allocation, and
 *     throwing allocates -- so Contains() answers a question and IndexOf()
 *     returns kNotAMember. A caller MUST branch on that answer. Substituting a
 *     nearby value instead is the degrade-to-something-close path 11 S13.6
 *     forbids, and it is forbidden here for the same reason as in Python: it
 *     turns a contract violation into ordinary-looking operation.
 *   * it does not say which sets carry an order. Two of them are decision
 *     orders in the contract and the arrays preserve their sequence, but
 *     "ordered" is a property recorded in sets.yaml and deliberately not
 *     mirrored here. A caller reading a rank off an array position would be
 *     inventing a priority for the sets that have none.
 *   * it holds no E_* code. Those are a separate table carrying four elements
 *     per row, with their own deployed header (CFG-CM-3).
 *   * it validates no combination. A domain name and a plane name are both
 *     members of their own sets and nothing here has an opinion on whether that
 *     pair names a legal key.
 */

#ifndef HACHIST_XBRAIN_V6_COMMON_ENUMS_CLOSED_SETS_H_
#define HACHIST_XBRAIN_V6_COMMON_ENUMS_CLOSED_SETS_H_

/* cstddef for size_t, string_view for the values, and nothing else. Every
 * include here is one every consumer pays for, and one of those consumers is on
 * a hop CRL-5 budgets at 200 microseconds. */
#include <cstddef>
#include <string_view>

namespace hachist {
namespace xbrain {
namespace enums {

/* Returned by IndexOf when the value is not in the set. It is NOT a member and
 * must never be used as one. Deliberately not zero: zero is a real position, and
 * for the ordered sets it is the STRONGEST one -- gate_limiter holds estop
 * there. A miss reported as zero would read as the highest-priority limiter. */
inline constexpr std::size_t kNotAMember = static_cast<std::size_t>(-1);

// arb_suspended -- 11 S7A.6.5   anchor: | 类型 | 生效路径 |
inline constexpr std::string_view kArbSuspended[] = {
    "soft_estop",
    "hes",
    "cmd_timeout",
};

// charge_stage -- 15 S8.5   anchor: | 取值 | 含义 | 退出条件 |
inline constexpr std::string_view kChargeStage[] = {
    "to_handover",
    "waiting_plug",
    "charging",
    "complete",
};

// cls -- 11 S3.1.1   anchor: 3.1.1 目标类别取值
inline constexpr std::string_view kCls[] = {
    "person",
    "vehicle",
    "bicycle",
    "motorcycle",
    "animal",
    "unknown",
};

// control_mode -- 11 S R2.6-f   anchor: 闭集章补 `control_mode` 一项
inline constexpr std::string_view kControlMode[] = {
    "jog",
};

// device -- 11 S5.1A   anchor: | 项 | `kind` |
inline constexpr std::string_view kDevice[] = {
    "rtk",
    "chassis",
    "cam_rgbd",
    "lidar",
    "ptz",
    "mic",
    "payload_speaker",
    "payload_siren",
    "payload_strobe",
    "payload_light",
};

// domain -- 11 S7A.0   anchor: | 域 | `domain` |
inline constexpr std::string_view kDomain[] = {
    "motion",
    "speaker",
    "asr",
    "payload_light",
    "ptz",
    "gpu",
    "dock",
};

// event_category -- 11 S6.2   anchor: | category | ... | channel |
inline constexpr std::string_view kEventCategory[] = {
    "intrusion",
    "fence",
    "speed_limit",
    "mode_change",
    "arbitration",
    "task",
    "charging",
    "health",
    "bit",
    "chassis",
    "estop",
    "comm",
    "rtk",
    "geo",
    "teach",
    "teleop",
    "perception",
    "motion",
    "payload",
    "data",
    "system",
    "ptz",
    "voice",
};

// fence_role -- 11 S9A.2   anchor: `polygons[].role` | string
inline constexpr std::string_view kFenceRole[] = {
    "allow",
    "forbid",
    "speed_limit",
    "warning",
};

// gate_limiter -- 11 S9.6.5   anchor: | 优先级 | `limiter` |
inline constexpr std::string_view kGateLimiter[] = {
    "estop",
    "mode",
    "health",
    "rtk",
    "heading",
    "clock",
    "fence",
    "free_space",
    "target",
    "brake",
    "gait",
    "profile",
    "spec",
    "none",
};

// gate_reason -- 11 S8.9.2   anchor: | `reason` 取值 | 含义 |
inline constexpr std::string_view kGateReason[] = {
    "open",
    "speaker_active",
    "tail_hold",
    "not_listening",
    "asr_not_granted",
    "device_fault",
    "manual_mute",
};

// geo_action -- 11 S7.9.1   anchor: | `action` | 语义 |
inline constexpr std::string_view kGeoAction[] = {
    "upsert",
    "delete",
    "rename",
    "set_state",
    "get",
    "list",
    "refs",
    "resync",
};

// geo_created_by -- 11 S7.8.2   anchor: | `created_by` / `updated_by` | string |
inline constexpr std::string_view kGeoCreatedBy[] = {
    "cloud",
    "hmi",
    "voice",
    "teach",
    "factory",
};

// geo_origin -- 11 S7.9.5   anchor: 云端 `cloud`
inline constexpr std::string_view kGeoOrigin[] = {
    "cloud",
    "wecom",
    "hmi",
    "voice",
};

// geo_state -- 11 S7.8.2   anchor: | `state` | string |
inline constexpr std::string_view kGeoState[] = {
    "draft",
    "active",
    "disabled",
    "deleted",
};

// geo_type -- 11 S7.8.2   anchor: | `type` | string |
inline constexpr std::string_view kGeoType[] = {
    "route",
    "waypoint",
    "fence",
    "dock",
};

// heading_source -- 11 S3.3   anchor: | `heading_source` | string |
inline constexpr std::string_view kHeadingSource[] = {
    "dual_antenna",
    "cog",
    "none",
};

// plane -- 11 S2.1   anchor: | `plane` |
inline constexpr std::string_view kPlane[] = {
    "rt",
    "state",
    "event",
    "cmd",
    "audio",
    "data",
    "health",
    "probe",
};

// reason -- 11 S R2.6-e   anchor: task/progress 的 reason 闭集
inline constexpr std::string_view kReason[] = {
    "rotation_blocked",
    "lateral_clearance_unavailable",
    "teleop_stale",
    "deadman_released",
};

// release_reason -- 11 S7A.1   anchor: | `release_reason` | string |
inline constexpr std::string_view kReleaseReason[] = {
    "done",
    "mode_exit",
    "user_cancel",
    "error",
};

// severity -- 11 S6.1 / S2.2.11   anchor: `{severity}` | `info`
inline constexpr std::string_view kSeverity[] = {
    "info",
    "warn",
    "alarm",
    "fault",
};

// stop_reason -- 11 S4.1   anchor: | `stop_reason` |
inline constexpr std::string_view kStopReason[] = {
    "none",
    "hes",
    "timeout",
    "soft_estop",
    "mode_switching",
    "mode_mismatch",
    "nan",
    "no_source",
};

// suspend_kind -- 11 S4.4   anchor: | `suspend_kind` | 触发 |
inline constexpr std::string_view kSuspendKind[] = {
    "passive",
    "yielding",
};

// suspend_reason -- 11 S4.4   anchor: | `suspend_reason` 闭集 |
inline constexpr std::string_view kSuspendReason[] = {
    "low_battery",
    "energy_unreachable",
    "estop_soft",
    "estop_hes",
    "clock_unsync",
    "rtk_degraded",
    "operator_pause",
    "unclean_shutdown",
    "shutdown_pending",
    "preempted",
    "mode_takeover",
};

// task_state -- 11 S4.4   anchor: | 分组 | `state` |
inline constexpr std::string_view kTaskState[] = {
    "pending",
    "scheduled",
    "blocked",
    "ready",
    "running",
    "suspended",
    "done",
    "failed",
    "cancelled",
    "interrupted",
    "wait_for_power_off",
    "needs_review",
};

/* Membership. constexpr, so a fixed value can be checked at compile time, and
 * allocation-free, so it is usable from the relay hop.
 *
 * Taken by reference to the array rather than as a pointer plus a length:
 * passing the length separately is how a caller ends up scanning one element
 * past the end of a set that was shortened by a regeneration. */
template <std::size_t N>
constexpr bool Contains(const std::string_view (&values)[N],
                        std::string_view value) {
  for (std::size_t i = 0; i < N; ++i) {
    if (values[i] == value) {
      return true;
    }
  }
  return false;
}

/* Position in contract order. Meaningful ONLY for the sets sets.yaml marks
 * ordered; for the rest the sequence is a table's typography and a rank read
 * from it is invented. Indices compare only within one set -- a gate_limiter
 * index measured against a stop_reason index is meaningless, and nothing here
 * can catch it, because both are plain size_t. */
template <std::size_t N>
constexpr std::size_t IndexOf(const std::string_view (&values)[N],
                              std::string_view value) {
  for (std::size_t i = 0; i < N; ++i) {
    if (values[i] == value) {
      return i;
    }
  }
  return kNotAMember;
}

}  // namespace enums
}  // namespace xbrain
}  // namespace hachist

#endif  // HACHIST_XBRAIN_V6_COMMON_ENUMS_CLOSED_SETS_H_
